### ISSUE TITLE
plex-wrapper: revisar uso de ellipsis en labels

### ISSUE THREAD

**Issue by andrrrl** [andes/plex#143]
Actualmente plex-wrapper está aplicando estas reglas:
```css
label {
    white-space: nowrap; 
    width: 190px; 
    overflow: hidden;
    text-overflow: ellipsis; 
}
```
Lo cual genera que no se puedan usar labels más descriptivos, aun cuando hay espacio de sobra.

![ellipsis](https://user-images.githubusercontent.com/11394455/78939298-3fa3db00-7a8a-11ea-8295-6be67e2bdb88.png)
